#ifndef ENUMS_H
#define ENUMS_H

enum {
    /*
    The names of the facelet positions of the cube
                    |************|
                    |*U1**U2**U3*|
                    |************|
                    |*U4**U5**U6*|
                    |************|
                    |*U7**U8**U9*|
                    |************|
        |************|************|************|************|
        |*L1**L2**L3*|*F1**F2**F3*|*R1**R2**R3*|*B1**B2**B3*|
        |************|************|************|************|
        |*L4**L5**L6*|*F4**F5**F6*|*R4**R5**R6*|*B4**B5**B6*|
        |************|************|************|************|
        |*L7**L8**L9*|*F7**F8**F9*|*R7**R8**R9*|*B7**B8**B9*|
        |************|************|************|************|
                    |************|
                    |*D1**D2**D3*|
                    |************|
                    |*D4**D5**D6*|
                    |************|
                    |*D7**D8**D9*|
                    |************|
        A cube definition string "UBL..." means for example: In position U1 we have the U-color, in position U2 we have the
        B-color, in position U3 we have the L color etc. according to the order U1, U2, U3, U4, U5, U6, U7, U8, U9, R1, R2,
        R3, R4, R5, R6, R7, R8, R9, F1, F2, F3, F4, F5, F6, F7, F8, F9, D1, D2, D3, D4, D5, D6, D7, D8, D9, L1, L2, L3, L4,
        L5, L6, L7, L8, L9, B1, B2, B3, B4, B5, B6, B7, B8, B9 of the enum constants.
    */
    U1, U2, U3, U4, U5, U6, U7, U8, U9,
    R1, R2, R3, R4, R5, R6, R7, R8, R9,
    F1, F2, F3, F4, F5, F6, F7, F8, F9,
    D1, D2, D3, D4, D5, D6, D7, D8, D9,
    L1, L2, L3, L4, L5, L6, L7, L8, L9,
    B1, B2, B3, B4, B5, B6, B7, B8, B9,
};

enum {
    // The possible colors of the cube facelets. Color U refers to the color of 
    // the U(p)-face etc. Also used to name the faces itself.
    U, R, F, D, L, B
};

enum {
    // The names of the corner positions of the cube. Corner URF e.g. has an U(p), a R(ight) and a F(ront) facelet.
    URF, UFL, ULB, UBR, DFR, DLF, DBL, DRB
};

enum {
    // The names of the edge positions of the cube. Edge UR e.g. has an U(p) and R(ight) facelet.
    UR, UF, UL, UB, DR, DF, DL, DB, FR, FL, BL, BR
};

enum {
    // The moves in the faceturn metric. Not to be confused with the names of the facelet positions in class Facelet.
    U1M, U2M, U3M, R1M, R2M, R3M, F1M, F2M, F3M, D1M, D2M, D3M, L1M, L2M, L3M, B1M, B2M, B3M
};

enum {
    // Basic symmetries of the cube. All 48 cube symmetries can be generated by sequences of these 4 symmetries.
    ROT_URF3, ROT_F2, ROT_U4, MIRR_LR2
};

#endif